theme: jekyll-theme-minimal
title: Shane Blinkman
description: A professional portfolio website showcasing my technical skills, professional experience, and project portfolio.
url: https://shaneblinkman.github.io
baseurl: ""
repository: https://github.com/shaneblinkman/shaneblinkman.github.io
google_analytics: UA-1234567890-1
google_analytics_id: UA-1234567890-1
google_analytics_id: UA-1234567890-1